--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.505.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 3/16/2021 2:13:00 PM
-- Server version: 10.4.17
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE vbac_stock;

--
-- Drop table `user_table`
--
DROP TABLE IF EXISTS user_table;

--
-- Drop table `return_table`
--
DROP TABLE IF EXISTS return_table;

--
-- Drop table `person_table`
--
DROP TABLE IF EXISTS person_table;

--
-- Drop table `stock_table`
--
DROP TABLE IF EXISTS stock_table;

--
-- Drop table `category_table`
--
DROP TABLE IF EXISTS category_table;

--
-- Set default database
--
USE vbac_stock;

--
-- Create table `category_table`
--
CREATE TABLE category_table (
  category_id INT(11) NOT NULL AUTO_INCREMENT,
  category_name VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (category_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 1,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create table `stock_table`
--
CREATE TABLE stock_table (
  stock_id INT(11) NOT NULL,
  stock_name VARCHAR(20) DEFAULT NULL,
  stock_amount INT(11) DEFAULT NULL,
  stock_category_id INT(11) DEFAULT NULL,
  stock_pic LONGTEXT DEFAULT NULL,
  PRIMARY KEY (stock_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create foreign key
--
ALTER TABLE stock_table 
  ADD CONSTRAINT FK_stock_table_category_table_category_id FOREIGN KEY (stock_category_id)
    REFERENCES category_table(category_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `person_table`
--
CREATE TABLE person_table (
  person_id INT(11) NOT NULL AUTO_INCREMENT,
  person_name VARCHAR(30) DEFAULT NULL,
  person_surname VARCHAR(30) DEFAULT NULL,
  person_date DATE DEFAULT NULL,
  PRIMARY KEY (person_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 1,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create table `return_table`
--
CREATE TABLE return_table (
  return_id INT(11) NOT NULL AUTO_INCREMENT,
  return_person_id INT(11) DEFAULT NULL,
  return_stock_id INT(11) DEFAULT NULL,
  return_amount INT(11) DEFAULT NULL,
  PRIMARY KEY (return_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 1,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create foreign key
--
ALTER TABLE return_table 
  ADD CONSTRAINT FK_return_table_person_table_person_id FOREIGN KEY (return_person_id)
    REFERENCES person_table(person_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE return_table 
  ADD CONSTRAINT FK_return_table_stock_table_stock_id FOREIGN KEY (return_stock_id)
    REFERENCES stock_table(stock_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `user_table`
--
CREATE TABLE user_table (
  user_name VARCHAR(20) NOT NULL,
  user_password VARCHAR(20) NOT NULL,
  PRIMARY KEY (user_name)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

-- 
-- Dumping data for table category_table
--
-- Table vbac_stock.category_table does not contain any data (it is empty)

-- 
-- Dumping data for table stock_table
--
-- Table vbac_stock.stock_table does not contain any data (it is empty)

-- 
-- Dumping data for table person_table
--
-- Table vbac_stock.person_table does not contain any data (it is empty)

-- 
-- Dumping data for table user_table
--
INSERT INTO user_table VALUES
('test', '1234');

-- 
-- Dumping data for table return_table
--
-- Table vbac_stock.return_table does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;